# Generated by Django 3.2.7 on 2021-10-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('shoppingCar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
