# Generated by Django 3.2.7 on 2021-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCar', '0003_auto_20211002_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(),
        ),
    ]
